### ISSUE TITLE
[TASK] Create a navigation bar.

### ISSUE THREAD

**Issue by anonna16** [QuangTran304/Instagram-Clone#28]
**Description**:  Create a static navigation bar. Try to use Material UI library to add icons. No need to add any functions for now.

**Details**:

- Navigation bar should contain the name of the application on the corner left.
- It should contain a search bar in the middle.
- On the right of the search bar, there should be a home button (static).
- On the right of the home button, there should be an arrow (direct messages).
- On the right of the arrow, there should be a heart (notifications).
- On the right corner, there should be the user's profile picture.

![image](https://user-images.githubusercontent.com/77517102/107163251-8bf3cc00-6976-11eb-9eee-b2de92b29deb.png)
 
**Story Points**: 3
**Priority**: High

**Comment by QuangTran304** [comment]
Task done!
