### ISSUE TITLE
[TASK] Create post prototypes.

### ISSUE THREAD

**Issue by anonna16** [QuangTran304/Instagram-Clone#29]
**Description**:  Create hardcoded posts.

**Details**:

- A post should have the user's profile picture on the top left corner.
- On the right of the profile picture, there should the user's username.
- Below the username, there should be a location (optional).
- Below all that, there should be the user's picture.
- Below the picture, there should be a heart next to bubble (comments) next to an arrow (direct message).
- Below that, there should be the user's username followed by the post description.
- At the bottom, there should be a comment section.

![image](https://user-images.githubusercontent.com/77517102/107163455-8cd92d80-6977-11eb-8b3c-6ef01ce04bbc.png)

**Story Points**: 5
**Priority**: High

**Comment by corinne-2000** [comment]
This task has been accomplished!
