### ISSUE TITLE
[TASK] Create a log-in popup form OR a separate login page

### ISSUE THREAD

**Issue by QuangTran304** [QuangTran304/Instagram-Clone#35]
**Description**: Create a login/ registration form (via a popup or a dedicated page) that allows new user to register & existing users can log-in. Ensure (by testing) the communication from our app to server happens smoothly, and vice-versa.

**Story Points**: 5
**Priority**: Medium

**Comment by tusharraval102** [comment]
Login page has been added, the navbar has been modified so that the links are useable. I also changed app.js so that we are able to use the router dom instead of it using traditional links. doesn't look like anything broke.

**Comment by tusharraval102** [comment]
The signin page and sign up page is up on master, taken from Material UI.
