### ISSUE TITLE
[TASK] Connect 'new user registration' info to Database 

### ISSUE THREAD

**Issue by QuangTran304** [QuangTran304/Instagram-Clone#39]
**Description**: Allow users to register / sign-up (using registration form)  ==>  Collect & push the information to our Cloud Firestore (Firebase Database).

This task already includes Check & Authenticate existing users (allow them to log-in if they already registered).

Story Points: 3
Risk: High
Priority: High

**Comment by tusharraval102** [comment]
Finish log in page to incorporate displayName.
